# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: route_guide.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "routeguide.Coordinate" do
    optional :latitude, :int32, 1
    optional :longitude, :int32, 2
  end
  add_message "routeguide.Area" do
    optional :lo, :message, 1, "routeguide.Coordinate"
    optional :hi, :message, 2, "routeguide.Coordinate"
  end
  add_message "routeguide.Location" do
    optional :name, :string, 1
    optional :coordinates, :message, 2, "routeguide.Coordinate"
  end
  add_message "routeguide.RouteNote" do
    optional :location, :message, 1, "routeguide.Coordinate"
    optional :message, :string, 2
  end
  add_message "routeguide.RouteSummary" do
    optional :locations_count, :int32, 2
    optional :distance, :int32, 3
    optional :elapsed_time, :int32, 4
  end
end

module Routeguide
  Coordinate = Google::Protobuf::DescriptorPool.generated_pool.lookup("routeguide.Coordinate").msgclass
  Area = Google::Protobuf::DescriptorPool.generated_pool.lookup("routeguide.Area").msgclass
  Location = Google::Protobuf::DescriptorPool.generated_pool.lookup("routeguide.Location").msgclass
  RouteNote = Google::Protobuf::DescriptorPool.generated_pool.lookup("routeguide.RouteNote").msgclass
  RouteSummary = Google::Protobuf::DescriptorPool.generated_pool.lookup("routeguide.RouteSummary").msgclass
end
